export type VolunteerDownloadEntity = {
  'Data de Submissão': Date;
  'ID Voluntário': number;
  Nome: string;
  'Data de Nascimento': Date;
  'E-mail': string;
  Telefone: string;
  País: string;
  Estado: string;
  Cidade: string;
  PcD: string;
  'PcD(Qual)': string;
  'Como nos achou ?': string;
  'Experiencia em workshops': string;
  Escolaridade: string;
  Curso1: string;
  Curso2: string;
  Conhecimentos: string;
  'Experiencia de vida': string;
  Desejos: string;
  Oportunidades: string;
  'Interesse em Posições Futuras': string;
  Declaração: string;
  'Habilidade de leitura': boolean | string;
  'Habilidade com livro': boolean | string;
  certificado: boolean | string;
  autorização: string;
};
