import { ENV } from './env';

export const DB_DATABASE = ENV.DB_DATABASE;
export const DB_USER = ENV.DB_USER;
export const DB_PASSWORD = ENV.DB_PASSWORD;
export const DB_HOST = ENV.DB_HOST;
export const DB_PORT: number = ENV.DB_PORT ? parseInt(ENV.DB_PORT) : 3306;
export const PORT = ENV.PORT ? parseInt(ENV.PORT) : 3000;
export const JWT_SECRET_KEY = ENV.JWT_SECRET_KEY;
export const ENCRYPTION_KEY = ENV.ENCRYPTION_KEY;

export const TLS =
  ENV.USE_TLS && ENV.TLS_KEY && ENV.TLS_CERT
    ? { key: ENV.TLS_KEY, cert: ENV.TLS_CERT }
    : null;

export const INFO_EMAIL = ENV.INFO_EMAIL;
export const HELPDESK_EMAIL = ENV.HELPDESK_EMAIL;
export const INFO_EMAIL_PASSWORD = ENV.INFO_EMAIL_PASSWORD;
export const RESET_PASSWORD_FRONTED_ROUTE = ENV.RESET_PASSWORD_FRONTED_ROUTE;
export const RESET_PASSWORD_FRONTEND_HOST = ENV.RESET_PASSWORD_FRONTEND_HOST;
export const GOOGLE_CLOUD_KEY = ENV.GOOGLE_CLOUD_KEY;
export const STORAGE_DOWNLOAD_FOLDER = ENV.STORAGE_DOWNLOAD_FOLDER;
export const NODE_ENV = ENV.NODE_ENV;
