const volunteerModel = {
  idvol: 1,
  idpep: 1,
  nome: 'test',
  cert: true,
  'habil-leitura': true,
  'habil-livro': true,
  author: 'test',
  'e-mail': 'test@gmail.com',
  senha: 'test',
  nascimento: new Date('2023-03-01T02:27:27.610Z'),
  telefone: 'test',
  'país': 'test',
  estado: 'test',
  cidade: 'test',
  etnia: 'test',
  defic: 'test',
  qual: 'test',
  genero: 'test',
  sexo: 'test',
  'nome social': 'test',
  ondesoube: 'test',
  'conhecimento pep': 'test',
  workshops: 'test',
  escolaridade: 'test',
  curso1: 'test',
  curso2: 'test',
  estudos: 'test',
  'experiências': 'test',
  sonhos: 'test',
  oportunidades: 'test',
  tempo: 20,
  dia: 'test',
  ajudar: 'test',
  contribuir: 'test',
  'declaração': 'test',
  createdAt: new Date('2023-03-01T02:27:27.610Z'),
}

export default volunteerModel