export default interface NotebooksEntity {
  idcad: number;
  idvol: number;
  idpep?: number;
  studentName: string;
  studentRegistration: number;
  studentPrisonUnit: string | undefined;
  evaluatorName: string;
  evaluatorEmail: string | undefined;
  subject1: string | undefined;
  subject2: string | undefined;
  subject3: string | undefined;
  subject4: string | undefined;
  subject5: string | undefined;
  subject6: string | undefined;
  subject7: string | undefined;
  subject8: string | undefined;
  subject9: string | undefined;
  subject10: string | undefined;
  relevantContent: string | undefined;
  a1: string | undefined;
  a2: string | undefined;
  a3: string | undefined;
  a4: string | undefined;
  a5: string | undefined;
  a6: string | undefined;
  a7: string | undefined;
  a8: string | undefined;
  a9: string | undefined;
  a10: string | undefined;
  a11: string | undefined;
  a12: string | undefined;
  a13: string | undefined;
  conclusion: string;
  archivesExclusion: boolean;
  evaluatedDate?: Date;
  reservationDate?: Date;
}
