name: Build and Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  upload-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repository files
      run: ls -l

    - name: Upload files and run commands
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
        ARGS: "-rlgoDzvc --delete" 
        SOURCE: "./" 
        REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }} 
        REMOTE_USER: ${{ secrets.SERVER_SSH_USER }} 
        TARGET: ${{ secrets.REMOTE_TARGET }} 
        SCRIPT_AFTER: |
          cd ${{ secrets.REMOTE_TARGET }}
          nvm use 17.9.0 
          npm pkg delete scripts.prepare
          npm i && npm i --dev
          npm run build
          cp .env build/ && cp ../server.key . && cp ../server.crt .
          mkdir build/src
          mkdir build/src/services
          mkdir build/src/services/email-service
          cp src/services/email-service/created-volunteer-body.html build/src/services/email-service
          cp src/services/email-service/created-volunteer-alternative-body.html build/src/services/email-service
          mkdir ./build/services/email-service/attachments
          cp ./src/services/email-service/attachments/ethicscode.pdf ./build/services/email-service/attachments
          pm2 restart palavrasdepaz
          echo "Deploy complete."
