name: Build and Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  upload-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repository files
      run: ls -l

    - name: Upload files and run commands
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} 
        ARGS: "-rlgoDzvc --delete" 
        SOURCE: "./" 
        REMOTE_HOST: ${{ secrets.SERVER_SSH_HOST }} 
        REMOTE_USER: ${{ secrets.SERVER_SSH_USER }} 
        TARGET: ${{ secrets.REMOTE_TARGET }} 
        SCRIPT_AFTER: |
          cd ${{ secrets.REMOTE_TARGET }}
          ${{ secrets.REMOTE_SCRIPT_AFTER }}
          echo "Deploy complete."
